version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    evironment:
      - PORT=3000
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - './mongodb-backup:/data/db'

networks:
  nestjs_network:
    driver: bridge
